# Generated by Django 4.0.6 on 2022-07-07 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('marca', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=60)),
                ('imagen', models.ImageField(upload_to='')),
            ],
        ),
    ]
